/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;
import BaseDatos.ConexionAccess;
import java.awt.image.ImageObserver;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

import java.sql.ResultSet;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author Hidan
 */
public class PrincipalContenedor extends javax.swing.JFrame {
ConexionAccess acc;
        public int sadul;
        public int ni;
        public int adulma;
        public int total;
        public String codigoBarra;
    /**
     * Creates new form PrincipalContenedor
     */
    public PrincipalContenedor() {
        initComponents();
        acc=ConexionAccess.getInstance();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFRAME_inicio = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jb_ingresar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jb_ingresar2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jb_salir2 = new javax.swing.JButton();
        try {
            Framecajero =(javax.swing.JFrame)java.beans.Beans.instantiate(getClass().getClassLoader(), "Programa.PrincipalContenedor_Framecajero");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jb_ingresar3 = new javax.swing.JButton();
        jb_volver = new javax.swing.JButton();
        AccesoCajero = new javax.swing.JLabel();
        Cajero = new javax.swing.JLabel();
        jtf_cajero = new javax.swing.JTextField();
        Clave = new javax.swing.JLabel();
        jtp_clave = new javax.swing.JPasswordField();
        FrameAdmi = new javax.swing.JFrame();
        jb_ingresar1212 = new javax.swing.JButton();
        jb_volver11 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jtf_usuarioadmi = new javax.swing.JTextField();
        jp_claveadmi = new javax.swing.JPasswordField();
        FrameVentas = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jb_ventaentradas = new javax.swing.JButton();
        jb_ventainternet = new javax.swing.JButton();
        jb_socios = new javax.swing.JButton();
        jb_salir4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        FrameEntradas = new javax.swing.JFrame();
        jb_adulto = new javax.swing.JButton();
        jb_niño = new javax.swing.JButton();
        jb_adulma = new javax.swing.JButton();
        jb_modedalocal = new javax.swing.JButton();
        jb_salir5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtf_adulto = new javax.swing.JTextField();
        jtf_niño = new javax.swing.JTextField();
        jtf_adulma = new javax.swing.JTextField();
        FrameMonedaLocal = new javax.swing.JFrame();
        jtf_MoneLocal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtf_valorEntra = new javax.swing.JTextField();
        jtf_vuelto = new javax.swing.JTextField();
        jb_vuelto1 = new javax.swing.JButton();
        jb_cancelar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jb_concretar = new javax.swing.JButton();
        FrameCodigoBarra = new javax.swing.JFrame();
        jtf_codigoBarra = new javax.swing.JTextField();
        jb_confirmar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FrameVentasInternet = new javax.swing.JFrame();
        jb_imprimirInternet = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtf_cdb = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtf_cdee = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtf_tde = new javax.swing.JTextField();
        jtf_vtc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        FrameSocio = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jtf_nombres = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtf_apellidos = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtf_rut = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtf_correo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtf_telefono = new javax.swing.JTextField();
        jb_verSocios = new javax.swing.JButton();
        jb_ingresarr = new javax.swing.JButton();
        jb_cancelarr = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        FrameVerSocio = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jtf_rut2 = new javax.swing.JTextField();
        jtf_nombres2 = new javax.swing.JTextField();
        jtf_apellidos2 = new javax.swing.JTextField();
        jtf_correo2 = new javax.swing.JTextField();
        jtf_telefono2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        jb_vollver = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        FrameAdministrador = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_ingresar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Acceso Cajero");

        jb_ingresar1.setText("Ingresar");
        jb_ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresar1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Acceso Administrador");

        jb_ingresar2.setText("Ingresar");
        jb_ingresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresar2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Elija Un Tipo De Acceso");

        jb_salir2.setText("Salir");
        jb_salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JFRAME_inicioLayout = new javax.swing.GroupLayout(JFRAME_inicio.getContentPane());
        JFRAME_inicio.getContentPane().setLayout(JFRAME_inicioLayout);
        JFRAME_inicioLayout.setHorizontalGroup(
            JFRAME_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFRAME_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JFRAME_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFRAME_inicioLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(JFRAME_inicioLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFRAME_inicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JFRAME_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_ingresar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_ingresar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_salir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );
        JFRAME_inicioLayout.setVerticalGroup(
            JFRAME_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFRAME_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_ingresar1)
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_ingresar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jb_salir2)
                .addContainerGap())
        );

        jb_ingresar3.setText("Ingresar");
        jb_ingresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresar3ActionPerformed(evt);
            }
        });

        jb_volver.setText("Volver");
        jb_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_volverActionPerformed(evt);
            }
        });

        AccesoCajero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccesoCajero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccesoCajero.setText("Acceso Cajero");

        Cajero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cajero.setText("Cajero :");

        jtf_cajero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Clave.setText("Clave    :");

        jtp_clave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout FramecajeroLayout = new javax.swing.GroupLayout(Framecajero.getContentPane());
        Framecajero.getContentPane().setLayout(FramecajeroLayout);
        FramecajeroLayout.setHorizontalGroup(
            FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramecajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccesoCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FramecajeroLayout.createSequentialGroup()
                        .addComponent(jb_ingresar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jb_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FramecajeroLayout.createSequentialGroup()
                        .addGroup(FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FramecajeroLayout.createSequentialGroup()
                                .addComponent(Cajero)
                                .addGap(18, 18, 18))
                            .addGroup(FramecajeroLayout.createSequentialGroup()
                                .addComponent(Clave)
                                .addGap(17, 17, 17)))
                        .addGroup(FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtp_clave, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jtf_cajero))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FramecajeroLayout.setVerticalGroup(
            FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FramecajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccesoCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cajero)
                    .addComponent(jtf_cajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clave)
                    .addComponent(jtp_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(FramecajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_volver)
                    .addComponent(jb_ingresar3))
                .addGap(19, 19, 19))
        );

        jb_ingresar1212.setText("Ingresar");
        jb_ingresar1212.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresar1212ActionPerformed(evt);
            }
        });

        jb_volver11.setText("Volver");
        jb_volver11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_volver11ActionPerformed(evt);
            }
        });

        jLabel31.setText("Password");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Acceso Administrador");

        jLabel33.setText("Usuario");

        javax.swing.GroupLayout FrameAdmiLayout = new javax.swing.GroupLayout(FrameAdmi.getContentPane());
        FrameAdmi.getContentPane().setLayout(FrameAdmiLayout);
        FrameAdmiLayout.setHorizontalGroup(
            FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAdmiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameAdmiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FrameAdmiLayout.createSequentialGroup()
                                .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_usuarioadmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp_claveadmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel32))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FrameAdmiLayout.createSequentialGroup()
                        .addComponent(jb_ingresar1212)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_volver11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        FrameAdmiLayout.setVerticalGroup(
            FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameAdmiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(24, 24, 24)
                .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jtf_usuarioadmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jp_claveadmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(FrameAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ingresar1212)
                    .addComponent(jb_volver11))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Elija Un Tipo De Venta o Gestion");

        jb_ventaentradas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_ventaentradas.setText("Venta Entradas");
        jb_ventaentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ventaentradasActionPerformed(evt);
            }
        });

        jb_ventainternet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_ventainternet.setText("Venta Internet");
        jb_ventainternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ventainternetActionPerformed(evt);
            }
        });

        jb_socios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_socios.setText("Socios");
        jb_socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sociosActionPerformed(evt);
            }
        });

        jb_salir4.setText("Salir");
        jb_salir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salir4ActionPerformed(evt);
            }
        });

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameVentasLayout = new javax.swing.GroupLayout(FrameVentas.getContentPane());
        FrameVentas.getContentPane().setLayout(FrameVentasLayout);
        FrameVentasLayout.setHorizontalGroup(
            FrameVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(FrameVentasLayout.createSequentialGroup()
                        .addComponent(jb_ventaentradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_socios, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_ventainternet, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameVentasLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_salir4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        FrameVentasLayout.setVerticalGroup(
            FrameVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(FrameVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ventainternet, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_socios, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ventaentradas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(FrameVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_salir4)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jb_adulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_adulto.setText("Adulto");
        jb_adulto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jb_adulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_adultoActionPerformed(evt);
            }
        });

        jb_niño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_niño.setText("Niño");
        jb_niño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jb_niño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_niñoActionPerformed(evt);
            }
        });

        jb_adulma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_adulma.setText("Adulto Mayor");
        jb_adulma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jb_adulma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_adulmaActionPerformed(evt);
            }
        });

        jb_modedalocal.setText("Modena Local");
        jb_modedalocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modedalocalActionPerformed(evt);
            }
        });

        jb_salir5.setText("Cancelar");
        jb_salir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salir5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ventas De Entradas");

        javax.swing.GroupLayout FrameEntradasLayout = new javax.swing.GroupLayout(FrameEntradas.getContentPane());
        FrameEntradas.getContentPane().setLayout(FrameEntradasLayout);
        FrameEntradasLayout.setHorizontalGroup(
            FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FrameEntradasLayout.createSequentialGroup()
                        .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_adulto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_modedalocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_adulto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameEntradasLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jb_salir5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameEntradasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_niño)
                                    .addComponent(jb_niño, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jb_adulma, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jtf_adulma))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        FrameEntradasLayout.setVerticalGroup(
            FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_adulma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_niño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_adulma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(FrameEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modedalocal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salir5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jLabel10.setText("Ingrese Moneda Local");

        jLabel11.setText("Valor Entradas");

        jb_vuelto1.setText("Vuelto");
        jb_vuelto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_vuelto1ActionPerformed(evt);
            }
        });

        jb_cancelar1.setText("Cancelar");
        jb_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelar1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Moneda Local");

        jb_concretar.setText("Concretar");
        jb_concretar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_concretarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameMonedaLocalLayout = new javax.swing.GroupLayout(FrameMonedaLocal.getContentPane());
        FrameMonedaLocal.getContentPane().setLayout(FrameMonedaLocalLayout);
        FrameMonedaLocalLayout.setHorizontalGroup(
            FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameMonedaLocalLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_MoneLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                        .addComponent(jb_concretar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                        .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                                .addComponent(jb_vuelto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)))
                        .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_valorEntra)
                            .addComponent(jtf_vuelto))))
                .addContainerGap())
            .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameMonedaLocalLayout.setVerticalGroup(
            FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMonedaLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(23, 23, 23)
                .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_MoneLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_valorEntra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_vuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_vuelto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(FrameMonedaLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancelar1)
                    .addComponent(jb_concretar))
                .addContainerGap())
        );

        jb_confirmar.setText("Confirmar");
        jb_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_confirmarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Codigo Barra");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameCodigoBarraLayout = new javax.swing.GroupLayout(FrameCodigoBarra.getContentPane());
        FrameCodigoBarra.getContentPane().setLayout(FrameCodigoBarraLayout);
        FrameCodigoBarraLayout.setHorizontalGroup(
            FrameCodigoBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameCodigoBarraLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(FrameCodigoBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameCodigoBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameCodigoBarraLayout.createSequentialGroup()
                        .addComponent(jtf_codigoBarra)
                        .addContainerGap())
                    .addGroup(FrameCodigoBarraLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(FrameCodigoBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        FrameCodigoBarraLayout.setVerticalGroup(
            FrameCodigoBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCodigoBarraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jb_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jb_imprimirInternet.setText("Imprimir");
        jb_imprimirInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_imprimirInternetActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtf_cdb.setEditable(false);

        jLabel14.setText("Codigo De Barra");

        jLabel15.setText("Cantidad De Entradas");

        jtf_cdee.setEditable(false);

        jLabel16.setText("Tipo De Entrada");

        jLabel17.setText("Valor Total Cancelado");

        jtf_tde.setEditable(false);

        jtf_vtc.setEditable(false);
        jtf_vtc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtf_vtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_vtcActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Datos Del Codigo");

        javax.swing.GroupLayout FrameVentasInternetLayout = new javax.swing.GroupLayout(FrameVentasInternet.getContentPane());
        FrameVentasInternet.getContentPane().setLayout(FrameVentasInternetLayout);
        FrameVentasInternetLayout.setHorizontalGroup(
            FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_cdb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                        .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jb_imprimirInternet)))
                        .addGap(18, 18, 18)
                        .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameVentasInternetLayout.createSequentialGroup()
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addComponent(jtf_vtc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_cdee, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_tde, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameVentasInternetLayout.setVerticalGroup(
            FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVentasInternetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(25, 25, 25)
                .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtf_cdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtf_tde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtf_cdee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtf_vtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(FrameVentasInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_imprimirInternet)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jLabel19.setText("Nombres");

        jLabel20.setText("Apellidos");

        jtf_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_apellidosActionPerformed(evt);
            }
        });

        jLabel21.setText("RUT");

        jLabel22.setText("Correo Electronico");

        jLabel23.setText("Telefono");

        jb_verSocios.setText("Ver Socios");
        jb_verSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_verSociosActionPerformed(evt);
            }
        });

        jb_ingresarr.setText("Ingresar Socio");
        jb_ingresarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresarrActionPerformed(evt);
            }
        });

        jb_cancelarr.setText("Volver");
        jb_cancelarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarrActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Registro De Socios");

        javax.swing.GroupLayout FrameSocioLayout = new javax.swing.GroupLayout(FrameSocio.getContentPane());
        FrameSocio.getContentPane().setLayout(FrameSocioLayout);
        FrameSocioLayout.setHorizontalGroup(
            FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameSocioLayout.createSequentialGroup()
                        .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(33, 33, 33)
                        .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_correo)
                            .addComponent(jtf_rut)
                            .addComponent(jtf_apellidos)
                            .addComponent(jtf_nombres)
                            .addComponent(jtf_telefono)))
                    .addGroup(FrameSocioLayout.createSequentialGroup()
                        .addComponent(jb_verSocios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_ingresarr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_cancelarr, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(FrameSocioLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameSocioLayout.setVerticalGroup(
            FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(26, 26, 26)
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtf_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jtf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameSocioLayout.createSequentialGroup()
                        .addGroup(FrameSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_verSocios)
                            .addComponent(jb_cancelarr))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameSocioLayout.createSequentialGroup()
                        .addComponent(jb_ingresarr)
                        .addGap(25, 25, 25))))
        );

        jLabel25.setText("RUT");

        jLabel26.setText("Nombres");

        jLabel27.setText("Apellidos");

        jLabel28.setText("Correo");

        jLabel29.setText("Telefono");

        jtf_nombres2.setEditable(false);

        jtf_apellidos2.setEditable(false);

        jtf_correo2.setEditable(false);

        jtf_telefono2.setEditable(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Buscar Socio");

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jb_vollver.setText("Volver");
        jb_vollver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_vollverActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameVerSocioLayout = new javax.swing.GroupLayout(FrameVerSocio.getContentPane());
        FrameVerSocio.getContentPane().setLayout(FrameVerSocioLayout);
        FrameVerSocioLayout.setHorizontalGroup(
            FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVerSocioLayout.createSequentialGroup()
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameVerSocioLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel30))
                    .addGroup(FrameVerSocioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameVerSocioLayout.createSequentialGroup()
                                .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jb_vollver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameVerSocioLayout.createSequentialGroup()
                                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(63, 63, 63)
                                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_correo2)
                                    .addComponent(jtf_apellidos2)
                                    .addComponent(jtf_nombres2)
                                    .addComponent(jtf_rut2)
                                    .addComponent(jtf_telefono2))))))
                .addContainerGap())
        );
        FrameVerSocioLayout.setVerticalGroup(
            FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVerSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(26, 26, 26)
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_rut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_apellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_correo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(FrameVerSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jb_vollver)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout FrameAdministradorLayout = new javax.swing.GroupLayout(FrameAdministrador.getContentPane());
        FrameAdministrador.getContentPane().setLayout(FrameAdministradorLayout);
        FrameAdministradorLayout.setHorizontalGroup(
            FrameAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameAdministradorLayout.setVerticalGroup(
            FrameAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestos De Ventas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestor De Ventas Para Parques ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("De Entretenciones");

        jLabel3.setText("Version 1.0");

        jb_ingresar.setText("Ingresar");
        jb_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresarActionPerformed(evt);
            }
        });

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga (1).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ingresar)
                    .addComponent(jb_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void suma(){
  //  String numero1=jtf_MoneLocal.getText();
    total=sadul+ni+adulma;
    jtf_valorEntra.setEditable(false);
    jtf_valorEntra.setText(total+"");
  //  int resta=total-Integer.parseInt(numero1);
   // if(resta >= total){
   //  jtf_vuelto.setText(resta+"");
   // }
    //else{
   //     jtf_vuelto.setText("");
   // }
   
}
public void limpiar(){
        jtf_nombres.setText("");
        jtf_apellidos.setText("");
        jtf_rut.setText("");
        jtf_correo.setText("");
        jtf_telefono.setText("");
}
public void limpiar2(){
        jtf_nombres2.setText("");
        jtf_apellidos2.setText("");
        jtf_rut2.setText("");
        jtf_correo2.setText("");
        jtf_telefono2.setText("");
}
    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jb_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresarActionPerformed
        // TODO add your handling code here:
        JFRAME_inicio.setVisible(true);
        JFRAME_inicio.pack();
        JFRAME_inicio.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jb_ingresarActionPerformed

    private void jb_salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salir2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jb_salir2ActionPerformed

    private void jb_ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresar1ActionPerformed
        // TODO add your handling code here:
        //JFRAME_inicio.setVisible(false);
        Framecajero.setVisible(true);
        Framecajero.pack();
        Framecajero.setLocationRelativeTo(this);
        jtf_cajero.requestFocus();
        
    }//GEN-LAST:event_jb_ingresar1ActionPerformed

    private void jb_ingresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresar2ActionPerformed
        // TODO add your handling code here:
        JFRAME_inicio.setVisible(false);
        FrameAdmi.setVisible(true);
        FrameAdmi.pack();
        FrameAdmi.setLocationRelativeTo(this);
                
    }//GEN-LAST:event_jb_ingresar2ActionPerformed

    private void jb_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_volverActionPerformed
        // TODO add your handling code here:
        Framecajero.setVisible(false);
        JFRAME_inicio.setVisible(true);
        JFRAME_inicio.pack();
        JFRAME_inicio.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jb_volverActionPerformed

    private void jb_ingresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresar3ActionPerformed
        // TODO add your handling code here:
       
        ResultSet rs=null;
        String cajero=jtf_cajero.getText();
        String clave=jtp_clave.getText();
        String sql="Select *from Usuario where nombre_cajero ='"+cajero+"';";
        rs=acc.ejecutarQuery(sql);
        try {
            if (rs.next())
            {
                String pass=rs.getString(3); 
                if (pass.equalsIgnoreCase(clave))
                {
                    JOptionPane.showMessageDialog(null,"Bienvenido");
                    JFRAME_inicio.setVisible(false);  
                    Framecajero.setVisible(false);
                    FrameVentas.setVisible(true);
                    FrameVentas.pack();
                    FrameVentas.setLocationRelativeTo(this);
                          
                }
                else
                {
                    JOptionPane.showMessageDialog(null," Clave Incorrecta");
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Usuario NO Existe");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }//GEN-LAST:event_jb_ingresar3ActionPerformed

    private void jb_salir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salir4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jb_salir4ActionPerformed

    private void jb_ventaentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ventaentradasActionPerformed
        // TODO add your handling code here:
        FrameVentas.setVisible(false);
        FrameEntradas.setVisible(true);
        FrameEntradas.pack();
        FrameEntradas.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_ventaentradasActionPerformed

    private void jb_salir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salir5ActionPerformed
        // TODO add your handling code here:
        FrameEntradas.setVisible(false);
        FrameVentas.setVisible(true);
        FrameVentas.pack();
        FrameVentas.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_salir5ActionPerformed

    private void jb_adultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_adultoActionPerformed
        // TODO add your handling code here:
      int adul=9000;
      sadul=sadul+adul;
      jtf_adulto.setText(+sadul+"");
      jtf_adulto.setEditable(false);
      

    }//GEN-LAST:event_jb_adultoActionPerformed

    private void jb_modedalocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modedalocalActionPerformed
        // TODO add your handling code here:
        FrameEntradas.setVisible(false);
        FrameMonedaLocal.setVisible(true);
        FrameMonedaLocal.pack();
        FrameMonedaLocal.setLocationRelativeTo(this);
       suma();
        
    }//GEN-LAST:event_jb_modedalocalActionPerformed

    private void jb_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelar1ActionPerformed
        // TODO add your handling code here:
        FrameMonedaLocal.setVisible(false);
        FrameEntradas.setVisible(true);
        FrameEntradas.pack();
        FrameEntradas.setLocationRelativeTo(this);
        jtf_valorEntra.setText("");
        jtf_adulto.setText("");
        jtf_niño.setText("");
        jtf_adulma.setText("");
        jtf_MoneLocal.setText("");
        jtf_vuelto.setText("");
        sadul=0;
        ni=0;
        adulma=0;
    }//GEN-LAST:event_jb_cancelar1ActionPerformed

    private void jb_niñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_niñoActionPerformed
        // TODO add your handling code here:
        int niñ=4000;
        ni=ni+niñ;
        jtf_niño.setText(+ni+"");
        jtf_niño.setEditable(false);
    }//GEN-LAST:event_jb_niñoActionPerformed

    private void jb_adulmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_adulmaActionPerformed
        // TODO add your handling code here:
        int adulmay=3000;
        adulma=adulma+adulmay;
        jtf_adulma.setText(+adulma+"");
        jtf_adulma.setEditable(false);
    }//GEN-LAST:event_jb_adulmaActionPerformed

    private void jb_vuelto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_vuelto1ActionPerformed
        // TODO add your handling code here:
          String numero1=jtf_MoneLocal.getText();
          total=sadul+ni+adulma;
           jtf_valorEntra.setEditable(false);
           jtf_valorEntra.setText(total+"");
          int resta=Integer.parseInt(numero1)-total;
           if(resta <= total){
           jtf_vuelto.setText(resta+"");
     }
     else{
          jtf_vuelto.setText(resta+"");
    }//GEN-LAST:event_jb_vuelto1ActionPerformed

    }
    private void jb_concretarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_concretarActionPerformed
        // TODO add your handling code here:
        
       // total=sadul+ni+adulma;
       // String pago=jtf_MoneLocal.getText()
       // int pago1=Integer.parseInt(pago)
        
       // if(total <= pago1){
            
      //  }
      
        
        JOptionPane.showMessageDialog(rootPane, "Imprimiendo Entradas y Boleta");
        jtf_valorEntra.setText("");
        jtf_adulto.setText("");
        jtf_niño.setText("");
        jtf_adulma.setText("");
        jtf_MoneLocal.setText("");
        jtf_vuelto.setText("");
        sadul=0;
        ni=0;
        adulma=0;
        FrameMonedaLocal.setVisible(false);
        FrameEntradas.setVisible(true);
        
        
        
    }//GEN-LAST:event_jb_concretarActionPerformed

    private void jb_ventainternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ventainternetActionPerformed
        // TODO add your handling code here:
        
        FrameVentas.setVisible(false);
        FrameCodigoBarra.setVisible (true);
        FrameCodigoBarra.pack();
        FrameCodigoBarra.setLocationRelativeTo(this);
        
        
        
    }//GEN-LAST:event_jb_ventainternetActionPerformed

    private void jb_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_confirmarActionPerformed
        // TODO add your handling code here:
        String cb;
        String cde;
        String tde;
        String vde;
        ResultSet rs=null;
        codigoBarra= jtf_codigoBarra.getText();
        String sql="Select *from codigo where codigo_barra ='"+codigoBarra+"';";
        rs=acc.ejecutarQuery(sql);
        try {
            if (rs.next())

                {
                    JOptionPane.showMessageDialog(null,"Codigo De Barra Correcto");
                    FrameCodigoBarra.setVisible(false);
                    FrameVentasInternet.setVisible(true);
                    FrameVentasInternet.pack();
                    FrameVentasInternet.setLocationRelativeTo(this);
                    //jtf_cdb.e
                    cb=rs.getString(1);
                    jtf_cdb.setText(cb);
                    cde=rs.getString(2);
                    jtf_cdee.setText(cde);
                    tde=rs.getString(4);
                    jtf_tde.setText(tde);
                    vde=rs.getString(3);
                    jtf_vtc.setText(vde);
                }
            else{
                JOptionPane.showMessageDialog(null,"El Codigo De Barra No Exite o Ya Fue Ocupado");
                jtf_codigoBarra.setText("");
            }
              
           
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
        
    }//GEN-LAST:event_jb_confirmarActionPerformed

    private void jtf_vtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_vtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_vtcActionPerformed

    private void jb_imprimirInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_imprimirInternetActionPerformed
        // TODO add your handling code here:
         ResultSet rs=null;
         String sql="select *from codigo";
        rs=acc.ejecutarQuery(sql);
        try {
            if (rs.next())

                {
                    
                    sql="Delete From codigo where codigo_barra='"+codigoBarra+"';";
                    acc.ejecutarIAE(sql);
                    JOptionPane.showMessageDialog(null,"Entrada Retirada Exitosamente");
                    FrameVentasInternet.setVisible(false);
                    FrameVentas.setVisible(true);
                }
            else{
                JOptionPane.showMessageDialog(null,"La Entrada No Existe");
            }
            
              
           
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }//GEN-LAST:event_jb_imprimirInternetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FrameVentasInternet.setVisible(false);
        FrameVentas.setVisible(true);
        FrameVentas.pack();
        FrameVentas.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrameCodigoBarra.setVisible(false);
        FrameVentas.setVisible(true);
        FrameVentas.pack();
        FrameVentas.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FrameVentas.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtf_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_apellidosActionPerformed

    private void jb_cancelarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarrActionPerformed
        // TODO add your handling code here:
        FrameSocio.setVisible(false);
        FrameVentas.setVisible(true);
        FrameVentas.pack();
        FrameVentas.setLocationRelativeTo(this);
        limpiar();
    }//GEN-LAST:event_jb_cancelarrActionPerformed

    private void jb_sociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sociosActionPerformed
        // TODO add your handling code here:
        FrameVentas.setVisible(false);
        FrameSocio.setVisible(true);
        FrameSocio.pack();
        FrameSocio.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_sociosActionPerformed

    private void jb_ingresarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresarrActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        String ru=jtf_rut.getText();
        String nom = jtf_nombres.getText();
        String ape = jtf_apellidos.getText();
        String cor=jtf_correo.getText();
        String tel= jtf_telefono.getText();
        String sql="select *from Socio";
        
        try {
            if (rs.next())

                {
                    
                 sql = "INSERT INTO Socio ("
                +"rut,"
                +"nombre,"
                +"apellido,"
                +"correo,"
                +"telefono)"
                +"VALUES('"
                +ru+"','"
                +nom+"','"
                +ape+"','"
                +cor+ "','"
                +tel+"')";
                  acc.ejecutarIAE(sql);
                 JOptionPane.showMessageDialog(null,"Entrada Retirada Exitosamente");
                }
          
            
              
           
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jb_ingresarrActionPerformed

    private void jb_verSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_verSociosActionPerformed
        // TODO add your handling code here:
        FrameSocio.setVisible(false);
        FrameVerSocio.setVisible(true);
        FrameVerSocio.pack();
        FrameVerSocio.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jb_verSociosActionPerformed

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        String rutsocio= jtf_rut2.getText();
        String ru;
        String no;
        String ap;
        String co;
        String te;
        String sql="Select *from Socio where rut ='"+rutsocio+"';";
        rs=acc.ejecutarQuery(sql);
        try {
            if (rs.next())

                {
                    JOptionPane.showMessageDialog(null,"Socio Encontrado");

                    ru=rs.getString(1);
                    jtf_rut2.setText(ru);
                    jtf_rut2.enable(false);
                    no=rs.getString(2);
                    jtf_nombres2.setText(no);
                    ap=rs.getString(3);
                    jtf_apellidos2.setText(ap);
                    co=rs.getString(4);
                    jtf_correo2.setText(co);
                    te=rs.getString(5);
                    jtf_telefono2.setText(te);
                }
            else{
                JOptionPane.showMessageDialog(null,"El Rut No Se Encuentra En La Base De Datos");
                jtf_codigoBarra.setText("");
            }
              
           
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        limpiar2();
        jtf_rut2.enable(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jb_vollverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_vollverActionPerformed
        // TODO add your handling code here:
        FrameVerSocio.setVisible(false);
        FrameSocio.setVisible(true);
        FrameSocio.pack();
        FrameSocio.setLocationRelativeTo(this);
        limpiar2();
    }//GEN-LAST:event_jb_vollverActionPerformed

    private void jb_ingresar1212ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresar1212ActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:
       
        ResultSet rs=null;
        String admi=jtf_usuarioadmi.getText();
        String clave2=jp_claveadmi.getText();
        String sql="Select *from admi where admi ='"+admi+"';";
        rs=acc.ejecutarQuery(sql);
        try {
            if (rs.next())
            {
                String pass=rs.getString(2); 
                if (pass.equalsIgnoreCase(clave2))
                {
                    JOptionPane.showMessageDialog(null,"Bienvenido");
                    JFRAME_inicio.setVisible(false);  
                    FrameAdmi.setVisible(false);
                    FrameAdministrador.setVisible(true);
                    FrameAdministrador.pack();
                    FrameAdministrador.setLocationRelativeTo(this);
                          
                }
                else
                {
                    JOptionPane.showMessageDialog(null," Clave Incorrecta");
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Usuario NO Existe");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }//GEN-LAST:event_jb_ingresar1212ActionPerformed

    private void jb_volver11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_volver11ActionPerformed
        // TODO add your handling code here:
        FrameAdmi.setVisible(false);
        JFRAME_inicio.setVisible(true);
        JFRAME_inicio.pack();
        JFRAME_inicio.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_volver11ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalContenedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccesoCajero;
    private javax.swing.JLabel Cajero;
    private javax.swing.JLabel Clave;
    private javax.swing.JFrame FrameAdmi;
    private javax.swing.JFrame FrameAdministrador;
    private javax.swing.JFrame FrameCodigoBarra;
    private javax.swing.JFrame FrameEntradas;
    private javax.swing.JFrame FrameMonedaLocal;
    private javax.swing.JFrame FrameSocio;
    private javax.swing.JFrame FrameVentas;
    private javax.swing.JFrame FrameVentasInternet;
    private javax.swing.JFrame FrameVerSocio;
    private javax.swing.JFrame Framecajero;
    private javax.swing.JFrame JFRAME_inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_adulma;
    private javax.swing.JButton jb_adulto;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar1;
    private javax.swing.JButton jb_cancelarr;
    private javax.swing.JButton jb_concretar;
    private javax.swing.JButton jb_confirmar;
    private javax.swing.JButton jb_imprimirInternet;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_ingresar1;
    private javax.swing.JButton jb_ingresar1212;
    private javax.swing.JButton jb_ingresar2;
    private javax.swing.JButton jb_ingresar3;
    private javax.swing.JButton jb_ingresarr;
    private javax.swing.JButton jb_modedalocal;
    private javax.swing.JButton jb_niño;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_salir2;
    private javax.swing.JButton jb_salir4;
    private javax.swing.JButton jb_salir5;
    private javax.swing.JButton jb_socios;
    private javax.swing.JButton jb_ventaentradas;
    private javax.swing.JButton jb_ventainternet;
    private javax.swing.JButton jb_verSocios;
    private javax.swing.JButton jb_vollver;
    private javax.swing.JButton jb_volver;
    private javax.swing.JButton jb_volver11;
    private javax.swing.JButton jb_vuelto1;
    private javax.swing.JPasswordField jp_claveadmi;
    private javax.swing.JTextField jtf_MoneLocal;
    private javax.swing.JTextField jtf_adulma;
    private javax.swing.JTextField jtf_adulto;
    private javax.swing.JTextField jtf_apellidos;
    private javax.swing.JTextField jtf_apellidos2;
    private javax.swing.JTextField jtf_cajero;
    private javax.swing.JTextField jtf_cdb;
    private javax.swing.JTextField jtf_cdee;
    private javax.swing.JTextField jtf_codigoBarra;
    private javax.swing.JTextField jtf_correo;
    private javax.swing.JTextField jtf_correo2;
    private javax.swing.JTextField jtf_niño;
    private javax.swing.JTextField jtf_nombres;
    private javax.swing.JTextField jtf_nombres2;
    private javax.swing.JTextField jtf_rut;
    private javax.swing.JTextField jtf_rut2;
    private javax.swing.JTextField jtf_tde;
    private javax.swing.JTextField jtf_telefono;
    private javax.swing.JTextField jtf_telefono2;
    private javax.swing.JTextField jtf_usuarioadmi;
    private javax.swing.JTextField jtf_valorEntra;
    private javax.swing.JTextField jtf_vtc;
    private javax.swing.JTextField jtf_vuelto;
    private javax.swing.JPasswordField jtp_clave;
    // End of variables declaration//GEN-END:variables
}